version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: dcwgpram/udacity-c3-docker-nginx 
  backend_user:
    build:
      context: ../../../02_microservices/udacity-c3-restapi-user
    image: dcwgpram/udacity-c3-restapi-user
  backend_feed:
    build:
      context: ../../../02_microservices/udacity-c3-restapi-feed  
    image: dcwgpram/udacity-c3-restapi-feed
  frontend:
    build:
      context: ../../../02_microservices/udacity-c3-frontend  
    image: dcwgpram/udacity-c3-frontend
