apiVersion: v1
kind: Pod
metadata:
  name: pod-backend-feed
spec:
  containers:
  - image: aleksdev/udacity-c3-restapi-feed
    name: pod-backend-feed
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "64Mi"
        cpu: "125m"
      limits:
        memory: "256Mi"
        cpu: "125m"       
    ports:
    - containerPort: 8080
  restartPolicy: Always